In [1]:
import numpy as np
import random
from itertools import islice   

In [2]:
""" 
    quality checks by analysing any queens in diagonal.
    We will select one row , loop through each rows and see the any element exist
    and counts the checksrelations
"""
def quality_check(list):
    column = 0
    q = 0
    row_index = 1
    for row in list:
        diff = row - (column + 1)
        row_index = 1         
        for col in range(column + 1,8):
            row1 = list[col]
            if ((row1 - row_index == row) | (row1 + row_index == row )):
                q = q + 1
            row_index = row_index + 1
        column = column + 1
    return q

In [3]:
"""
  Initialize the parents with value between 1 - 8 and unique number
"""
def initialize():
    no_population = 5
    population = []
    for p_no in range(0, no_population):
        pop = random.sample(range(1,9), 8)
        population.append(pop)
    return population

In [4]:
def parent_selection(population):
    quality = {}
    index = 0
    
    for pop in population:
        q1 = quality_check(pop)
        quality[index] = q1
        index = index + 1
    #""" make dict and sort """
    quality1 = {k: v for k, v in sorted(quality.items(), key=lambda item: item[1])}
    first, second = islice(quality1.keys(), 2)  
    
    parent1 = population[first]
    parent2 = population[second]
    
    return parent1, parent2

    
    

In [5]:
def partial_mapped_crossover(parent1, parent2):
    

    firstCrossPoint = np.random.randint(0,len(parent1)-2)
    secondCrossPoint = np.random.randint(firstCrossPoint+1,len(parent1)-1)

    print(firstCrossPoint, secondCrossPoint)

    parent1MiddleCross = parent1[firstCrossPoint:secondCrossPoint]
    parent2MiddleCross = parent2[firstCrossPoint:secondCrossPoint]

    temp_child1 = parent1[:firstCrossPoint] + parent2MiddleCross + parent1[secondCrossPoint:]

    temp_child2 = parent2[:firstCrossPoint] + parent1MiddleCross + parent2[secondCrossPoint:]

    relations = []
    for i in range(len(parent1MiddleCross)):
        relations.append([parent2MiddleCross[i], parent1MiddleCross[i]])

    print(relations)

    

    child1=recursion1(temp_child1,firstCrossPoint,secondCrossPoint,parent1MiddleCross,parent2MiddleCross, relations)
    child2=recursion2(temp_child2,firstCrossPoint,secondCrossPoint,parent1MiddleCross,parent2MiddleCross, relations)

    print(child1)
    print(child2)
    
    return [list(child1), list(child2)]
    

In [6]:
def recursion1 (temp_child , firstCrossPoint , secondCrossPoint , parent1MiddleCross , parent2MiddleCross, relations) :
    child = np.array([0 for i in range(len(parent1))])
    for i,j in enumerate(temp_child[:firstCrossPoint]):
        c=0
        for x in relations:
            if j == x[0]:
                child[i]=x[1]
                c=1
                break
        if c==0:
            child[i]=j
    j=0
    for i in range(firstCrossPoint,secondCrossPoint):
        child[i]=parent2MiddleCross[j]
        j+=1

    for i,j in enumerate(temp_child[secondCrossPoint:]):
        c=0
        for x in relations:
            if j == x[0]:
                child[i+secondCrossPoint]=x[1]
                c=1
                break
        if c==0:
            child[i+secondCrossPoint]=j
    child_unique=np.unique(child)
    if len(child)>len(child_unique):
        child=recursion1(child,firstCrossPoint,secondCrossPoint,parent1MiddleCross,parent2MiddleCross, relations)
    return(child)

In [7]:

def recursion2(temp_child,firstCrossPoint,secondCrossPoint,parent1MiddleCross,parent2MiddleCross, relations):
    child = np.array([0 for i in range(len(parent1))])
    for i,j in enumerate(temp_child[:firstCrossPoint]):
        c=0
        for x in relations:
            if j == x[1]:
                child[i]=x[0]
                c=1
                break
        if c==0:
            child[i]=j
    j=0
    for i in range(firstCrossPoint,secondCrossPoint):
        child[i]=parent1MiddleCross[j]
        j+=1

    for i,j in enumerate(temp_child[secondCrossPoint:]):
        c=0
        for x in relations:
            if j == x[1]:
                child[i+secondCrossPoint]=x[0]
                c=1
                break
        if c==0:
            child[i+secondCrossPoint]=j
    child_unique=np.unique(child)
    if len(child)>len(child_unique):
        child=recursion2(child,firstCrossPoint,secondCrossPoint,parent1MiddleCross,parent2MiddleCross, relations)
    return(child)

In [8]:
"""
 One point cross over , cut and cross over
"""
def cross_over(child1, child2):
 
    index = random.randint(0,7)
    
    for i in range(index, 8): 
        child1[i], child2[i] = child2[i], child1[i] 
    
    return [child1, child2]

In [9]:
"""
 Swap mutate
"""
def mutate_swap(child):
    r1, r2 = random.sample(range(0, 7), 2)
    print(r1)
    print(r2)
    child[r1], child[r2] = child[r2], child[r1]
    return child
    

In [10]:
def add_to_population(population, child1, child2):
    population.append(child1)
    population.append(child2)
    return population

In [11]:
def survival_fitness(population):
    quality = {}
    index = 0
    
    for pop in population:
        q1 = quality_check(pop)
        quality[index] = q1
        index = index + 1
    """ make dict and sort """
    quality1 = {k: v for k, v in sorted(quality.items(), key=lambda item: item[1], reverse=True)}
    print(quality1)
    first, second = islice(quality1.keys(), 2)  
    
    p1 = population[first]
    p2 = population[second]
    
    print(p1)
    print(p2)
    
    population.remove(p1)
    population.remove(p2)
    
    print(population)
    return population
    

In [15]:
population = initialize()

In [16]:
population

[[7, 6, 2, 5, 4, 1, 8, 3],
 [3, 8, 6, 1, 7, 5, 2, 4],
 [7, 4, 1, 3, 5, 8, 6, 2],
 [5, 8, 2, 4, 3, 6, 1, 7],
 [3, 1, 5, 4, 7, 6, 8, 2]]

In [17]:
isOptimumSolution = False

bestresult = None
quality = 0

for i in range(0, 100001):
    
    parent1, parent2 = parent_selection(population)
               
    bestresult = parent1
            
    quality = quality_check(bestresult)
    
    if( quality == 0):
               
        isOptimumSolution = True
        print( "iteration =", i)
        print("No of checks = ", quality)
        print(bestresult)
        break
        
    else:
        
        #child1, child2 = cross_over(parent1,parent2)
        child1, child2 = partial_mapped_crossover(parent1,parent2)
        
        child1 = mutate_swap(child1)
        child2 = mutate_swap(child2)
        
        population  = add_to_population(population, child1, child2)
        population  = survival_fitness(population)


if(isOptimumSolution == False):
    print("Number of checks =", quality)
    print("Available best solutions")
    print(bestresult)
        
        
    
    
    

1 4
[[4, 8], [1, 6], [3, 1]]
[6 4 1 3 7 5 2 8]
[7 8 6 1 5 4 3 2]
1
6
0
6
{6: 7, 4: 6, 0: 5, 3: 5, 5: 5, 1: 3, 2: 3}
[3, 8, 6, 1, 5, 4, 7, 2]
[3, 1, 5, 4, 7, 6, 8, 2]
[[7, 6, 2, 5, 4, 1, 8, 3], [3, 8, 6, 1, 7, 5, 2, 4], [7, 4, 1, 3, 5, 8, 6, 2], [5, 8, 2, 4, 3, 6, 1, 7], [6, 2, 1, 3, 7, 5, 4, 8]]
2 3
[[1, 6]]
[3 8 1 6 7 5 2 4]
[7 4 6 3 5 8 1 2]
1
3
6
0
{5: 6, 6: 6, 0: 5, 3: 5, 4: 5, 1: 3, 2: 3}
[3, 6, 1, 8, 7, 5, 2, 4]
[1, 4, 6, 3, 5, 8, 7, 2]
[[7, 6, 2, 5, 4, 1, 8, 3], [3, 8, 6, 1, 7, 5, 2, 4], [7, 4, 1, 3, 5, 8, 6, 2], [5, 8, 2, 4, 3, 6, 1, 7], [6, 2, 1, 3, 7, 5, 4, 8]]
0 3
[[7, 3], [4, 8], [1, 6]]
[7 4 1 6 3 5 2 8]
[3 8 6 7 5 4 1 2]
6
4
5
3
{6: 6, 0: 5, 3: 5, 4: 5, 1: 3, 2: 3, 5: 2}
[3, 8, 6, 4, 5, 7, 1, 2]
[7, 6, 2, 5, 4, 1, 8, 3]
[[3, 8, 6, 1, 7, 5, 2, 4], [7, 4, 1, 3, 5, 8, 6, 2], [5, 8, 2, 4, 3, 6, 1, 7], [6, 2, 1, 3, 7, 5, 4, 8], [7, 4, 1, 6, 2, 5, 3, 8]]
1 2
[[8, 4]]
[7 8 1 6 2 5 3 4]
[3 4 6 1 7 5 2 8]
0
5
5
4
{2: 5, 3: 5, 5: 4, 0: 3, 1: 3, 6: 3, 4: 2}
[5, 8, 2, 4, 3, 6, 1, 7]


5 6
[[7, 7]]
[8 5 2 6 3 7 1 4]
[8 5 2 6 3 7 1 4]
4
0
1
2
{6: 4, 5: 3, 0: 1, 1: 1, 2: 1, 3: 1, 4: 1}
[8, 2, 5, 6, 3, 7, 1, 4]
[3, 5, 2, 6, 8, 7, 1, 4]
[[8, 5, 2, 6, 3, 7, 1, 4], [8, 5, 2, 6, 3, 7, 1, 4], [5, 3, 8, 6, 2, 7, 1, 4], [5, 7, 2, 6, 8, 3, 1, 4], [5, 8, 2, 6, 3, 1, 7, 4]]
5 6
[[7, 7]]
[8 5 2 6 3 7 1 4]
[8 5 2 6 3 7 1 4]
0
3
5
2
{6: 5, 5: 3, 0: 1, 1: 1, 2: 1, 3: 1, 4: 1}
[8, 5, 7, 6, 3, 2, 1, 4]
[6, 5, 2, 8, 3, 7, 1, 4]
[[8, 5, 2, 6, 3, 7, 1, 4], [8, 5, 2, 6, 3, 7, 1, 4], [5, 3, 8, 6, 2, 7, 1, 4], [5, 7, 2, 6, 8, 3, 1, 4], [5, 8, 2, 6, 3, 1, 7, 4]]
5 6
[[7, 7]]
[8 5 2 6 3 7 1 4]
[8 5 2 6 3 7 1 4]
2
4
6
3
{6: 3, 0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1}
[8, 5, 2, 1, 3, 7, 6, 4]
[8, 5, 2, 6, 3, 7, 1, 4]
[[8, 5, 2, 6, 3, 7, 1, 4], [5, 3, 8, 6, 2, 7, 1, 4], [5, 7, 2, 6, 8, 3, 1, 4], [5, 8, 2, 6, 3, 1, 7, 4], [8, 5, 3, 6, 2, 7, 1, 4]]
2 6
[[8, 2], [6, 6], [2, 3], [7, 7]]
[3 5 8 6 2 7 1 4]
[5 8 2 6 3 7 1 4]
6
2
0
4
{5: 4, 6: 4, 0: 1, 1: 1, 2: 1, 3: 1, 4: 1}
[3, 5, 1, 6, 2, 7, 8, 4]
[3, 8, 2

[5 8 2 6 3 1 7 4]
[5 2 8 6 3 1 7 4]
1
4
0
1
{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1}
[5, 2, 8, 6, 3, 1, 7, 4]
[5, 8, 2, 6, 3, 1, 7, 4]
[[5, 2, 8, 1, 3, 7, 6, 4], [5, 2, 8, 6, 3, 7, 1, 4], [5, 8, 2, 7, 3, 1, 6, 4], [5, 3, 2, 6, 8, 1, 7, 4], [2, 5, 8, 6, 3, 1, 7, 4]]
4 6
[[3, 3], [7, 7]]
[5 2 8 1 3 7 6 4]
[5 2 8 6 3 7 1 4]
1
3
6
3
{5: 4, 0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 6: 1}
[5, 1, 8, 2, 3, 7, 6, 4]
[5, 2, 8, 1, 3, 7, 6, 4]
[[5, 2, 8, 6, 3, 7, 1, 4], [5, 8, 2, 7, 3, 1, 6, 4], [5, 3, 2, 6, 8, 1, 7, 4], [2, 5, 8, 6, 3, 1, 7, 4], [5, 2, 8, 1, 3, 7, 6, 4]]
3 4
[[7, 6]]
[5 2 8 7 3 6 1 4]
[5 8 2 6 3 1 7 4]
1
0
3
1
{6: 5, 5: 4, 0: 1, 1: 1, 2: 1, 3: 1, 4: 1}
[5, 6, 2, 8, 3, 1, 7, 4]
[2, 5, 8, 7, 3, 6, 1, 4]
[[5, 2, 8, 6, 3, 7, 1, 4], [5, 8, 2, 7, 3, 1, 6, 4], [5, 3, 2, 6, 8, 1, 7, 4], [2, 5, 8, 6, 3, 1, 7, 4], [5, 2, 8, 1, 3, 7, 6, 4]]
1 3
[[8, 2], [2, 8]]
[5 8 2 6 3 7 1 4]
[5 2 8 7 3 1 6 4]
2
6
1
2
{5: 2, 0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 6: 1}
[5, 8, 1, 6, 3, 7, 2, 4]
[5, 2, 8, 6, 3, 7, 1, 4]
[[5,